server:
  port: 6601


spring:

    servlet:
      multipart:
        max-file-size: 1024Mb
        max-request-size: 1024Mb

    datasource:
        name: lottery
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://59.110.240.36:3306/lottery?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
          username: root
          password: root_
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.christmas.demo.model
  config-location: classpath:mybatis/mybatis-config.xml

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
logging:
  level:
    com:
      lottery:
          dao: debug
  file: logs/spring-boot-logging.log


file:
  image: jpg,bmp,gif,png
  video: avi,mov,mpeg,mp4

locationpath: D:/upload/

wechat:
  appid: wx18526bcd31d54c1f
  mechid: 1522692361
  key: jiangfengqingxiaochengxu12345678
  payip: 118.24.207.16
  notifyUrl: https://aiyuanmqz.com/business/buycallback
  unifiedorderUrl: https://api.mch.weixin.qq.com/pay/unifiedorder
  secret: ffadd8817f1014de60e754f2a85099fd

